server/src/main/kotlin/gg/airbrush/server/plugins/PluginManager.kt
Enabling plugins was not synchronous, but instead was scheduled for the next tick. This allowed plugins to be enabled more than once (which is not good).
=> Fix plugins loading multiple times

server/src/main/kotlin/gg/airbrush/server/Main.kt
Sets the server favicon from `server-icon.png`
=> Add server favicon icon

server/src/main/kotlin/gg/airbrush/server/lib/MiniMessage.kt
=> fix: add missing default tags

core/src/main/kotlin/gg/airbrush/core/commands/Create.kt, core/src/main/kotlin/gg/airbrush/core/lib/CanvasManager.kt, core/src/main/kotlin/gg/airbrush/core/lib/Sidebar.kt
Adds a feedback message for canvas world creation, and improves displaying world names in the scoreboard.
Resolves AIR-1.
=> Canvas world improvements

core/src/main/kotlin/gg/airbrush/core/events/PlayerLogin.kt
=> Prevent duplicate join messages

sdk/src/main/kotlin/gg/airbrush/sdk/classes/ranks/Ranks.kt
improves first time development experience
=> chore(sdk): create Default rank if it doesn't exist

discord/src/main/kotlin/gg/airbrush/discord/discordCommands/LinkCommand.kt, discord/src/main/kotlin/gg/airbrush/discord/events/PlayerChat.kt, discord/src/main/kotlin/gg/airbrush/discord/events/PlayerJoin.kt, discord/src/main/kotlin/gg/airbrush/discord/lib/Placeholder.kt, discord/src/main/resources/config.toml
fixes the bug that prevents in-game join / leave messages from being broadcasted into discord
=> fix(discord): discord join / leave messages

core/src/main/kotlin/gg/airbrush/core/Core.kt, core/src/main/kotlin/gg/airbrush/core/commands/Rules.kt, sdk/src/main/resources/translations.toml
improves rules layout & fetches them from a config instead
=> chore(rules): fetch rules from config

core/src/main/kotlin/gg/airbrush/core/events/PlayerChat.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/PunishCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/PunishmentsCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/RevertPunishmentCommand.kt, server/src/main/kotlin/gg/airbrush/server/commands/Stop.kt, server/src/main/kotlin/gg/airbrush/server/commands/plugins/Disable.kt, server/src/main/kotlin/gg/airbrush/server/commands/plugins/Enable.kt, server/src/main/kotlin/gg/airbrush/server/commands/plugins/Reload.kt
generalizes permission nodes to be more consistent, and adds full support for mod rank
=> full support for mod rank

core/src/main/kotlin/gg/airbrush/core/commands/TestColors.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/BanCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/KickCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/MuteCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/PunishCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/RevertPunishmentCommand.kt, sdk/src/main/kotlin/gg/airbrush/sdk/SDKPlugin.kt, sdk/src/main/kotlin/gg/airbrush/sdk/lib/InputHandler.kt
implements an input handler for fetching input from the chat box, and uses this for reversions. additionally, this PR also includes error handling for punishment issuing
=> Implement place to write reason for revert

punishments/build.gradle.kts, punishments/src/main/kotlin/gg/airbrush/punishments/Punishments.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/EditPunishmentCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/PunishmentCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/RevertPunishmentCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/lib/Punishment.kt, sdk/src/main/kotlin/gg/airbrush/sdk/classes/punishments/AirbrushPunishment.kt, sdk/src/main/kotlin/gg/airbrush/sdk/lib/InputHandler.kt, sdk/src/main/resources/translations.toml
implement punishment editing & other tiny fixes
=> feat: edit punishment command

punishments/src/main/kotlin/gg/airbrush/punishments/Punishments.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/PunishCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/lib/Punishment.kt
implements punishment duration scaling
=> punishment duration scaling

sdk/src/main/kotlin/gg/airbrush/sdk/classes/punishments/Punishments.kt
implements caching within the punishment list. 
the punishment list is called on join and within chat events. once they join, it's cached for the entirety of their stay (unless they get punished) - making other calls to the punishment list miniscule
=> feat: implement punishment list cache

discord/src/main/kotlin/gg/airbrush/discord/discordCommands/WhitelistCommand.kt, discord/src/main/kotlin/gg/airbrush/discord/lib/Constants.kt
fixes permissions within commands
=> fix: permissions

core/src/main/kotlin/gg/airbrush/core/events/BrushEvents.kt, sdk/src/main/kotlin/gg/airbrush/sdk/classes/players/AirbrushPlayer.kt
=> Brush events bug fixes

punishments/src/main/resources/punishments.toml, worlds/src/main/resources/worlds.toml
updates internal worlds & punishments config to account for previous changes
=> chore: update internal resources

core/src/main/kotlin/gg/airbrush/core/Core.kt, core/src/main/kotlin/gg/airbrush/core/commands/BrushGUI.kt, core/src/main/kotlin/gg/airbrush/core/commands/Whitelist.kt, core/src/main/kotlin/gg/airbrush/core/commands/history/History.kt, core/src/main/kotlin/gg/airbrush/core/commands/mainmenu/PlayerSettings.kt, core/src/main/kotlin/gg/airbrush/core/commands/mainmenu/SelectWorld.kt, core/src/main/kotlin/gg/airbrush/core/commands/worlds/Canvas.kt, core/src/main/kotlin/gg/airbrush/core/lib/IntExt.kt, core/src/main/kotlin/gg/airbrush/core/lib/PlayerExt.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/EditPunishmentCommand.kt, sdk/src/main/kotlin/gg/airbrush/sdk/lib/CooldownHandler.kt, sdk/src/main/kotlin/gg/airbrush/sdk/lib/General.kt
Tiny improvements and changes, cooldowns & debounce implementation
=> chore: misc improvements

core/src/main/kotlin/gg/airbrush/core/Core.kt, core/src/main/kotlin/gg/airbrush/core/commands/worlds/WorldSettings.kt, sdk/src/main/kotlin/gg/airbrush/sdk/classes/worlds/AirbrushWorld.kt, sdk/src/main/kotlin/gg/airbrush/sdk/lib/InputHandler.kt, worlds/src/main/kotlin/gg/airbrush/worlds/WorldManager.kt, worlds/src/main/kotlin/gg/airbrush/worlds/listener/GlobalEventListeners.kt
Implements world renaming, world deletion, world privacy, and the ability to change your gamemode within your world.
=> feat: the great world update™️

core/src/main/kotlin/gg/airbrush/core/Core.kt, core/src/main/kotlin/gg/airbrush/core/commands/admin/Admin.kt, core/src/main/kotlin/gg/airbrush/core/commands/worlds/WorldSettings.kt, sdk/src/main/kotlin/gg/airbrush/sdk/classes/worlds/Worlds.kt
Implements /admin, with the ability to view current world information as well as delete the world they're currently in
=> feat: ability for admins to delete worlds

punishments/src/main/kotlin/gg/airbrush/punishments/events/PlayerEvents.kt, punishments/src/main/kotlin/gg/airbrush/punishments/lib/Punishment.kt, sdk/src/main/kotlin/gg/airbrush/sdk/classes/punishments/AirbrushPunishment.kt, sdk/src/main/kotlin/gg/airbrush/sdk/classes/punishments/Punishments.kt
fixes punishments not applying by properly using the UUID type within mongo
=> fix: punishments not applying to players

sdk/src/main/kotlin/gg/airbrush/sdk/classes/punishments/AirbrushPunishment.kt, sdk/src/main/kotlin/gg/airbrush/sdk/classes/punishments/Punishments.kt
clears punishment cache for player upon update
=> fix cache issues

core/src/main/kotlin/gg/airbrush/core/commands/admin/Broadcast.kt, core/src/main/kotlin/gg/airbrush/core/events/PlayerChat.kt, discord/src/main/kotlin/gg/airbrush/discord/Discord.kt, discord/src/main/kotlin/gg/airbrush/discord/UseBot.kt, punishments/src/main/kotlin/gg/airbrush/punishments/commands/RevertPunishmentCommand.kt, punishments/src/main/kotlin/gg/airbrush/punishments/lib/Punishment.kt
implements useBot for using the discord bot functionality
=> feat: implement useBot

core/src/main/kotlin/gg/airbrush/core/Core.kt, core/src/main/kotlin/gg/airbrush/core/commands/Hardware.kt, core/src/main/kotlin/gg/airbrush/core/events/PlayerLogin.kt, worlds/src/main/kotlin/gg/airbrush/worlds/WorldManager.kt, worlds/src/main/resources/worlds.toml
Also, adds a header and footer to the tablist.
Resolves AIR-55.
=> Add ranks and levels to tablist

core/src/main/kotlin/gg/airbrush/core/Core.kt, core/src/main/kotlin/gg/airbrush/core/commands/Shop.kt, core/src/main/kotlin/gg/airbrush/core/commands/mainmenu/MainMenu.kt
implements tebex shop into main menu
=> feat: add shop

core/src/main/kotlin/gg/airbrush/core/events/PlayerChat.kt, sdk/src/main/kotlin/gg/airbrush/sdk/Database.kt
=> chore: dev env changes

core/src/main/kotlin/gg/airbrush/core/events/PlayerLevelUp.kt, core/src/main/kotlin/gg/airbrush/core/events/PlayerLogin.kt, core/src/main/kotlin/gg/airbrush/core/lib/PlayerExt.kt
=> Update tab list when player levels up

core/src/main/kotlin/gg/airbrush/core/events/PlayerLogin.kt, core/src/main/kotlin/gg/airbrush/core/lib/PlayerExt.kt
=> Sort tablist based on rank + disable collision

core/build.gradle.kts, core/src/main/kotlin/gg/airbrush/core/Core.kt, core/src/main/kotlin/gg/airbrush/core/commands/PortMongo.kt, core/src/main/kotlin/gg/airbrush/core/commands/Stats.kt, core/src/main/kotlin/gg/airbrush/core/commands/history/History.kt, dev-env/.gitignore, dev-env/docker-compose.yml, sdk/build.gradle.kts, sdk/src/main/kotlin/gg/airbrush/sdk/classes/pixels/Pixels.kt, server/build.gradle.kts
Complete rewrite of our pixel SDK to SQLite using Iron. This should improve performance by a landslide and also alleviate a lot of the bugs we've been recently experiencing.
=> Pixel sql migration

core/src/main/kotlin/gg/airbrush/core/commands/admin/Admin.kt, worlds/src/main/kotlin/gg/airbrush/worlds/WorldManager.kt, worlds/src/main/kotlin/gg/airbrush/worlds/Worlds.kt
We now save all of the worlds every minute, along with the introduction of `/admin saveworld`
=> chore(worlds): improve saving
